### PR TITLE
Bump for `try`

### PR DESCRIPTION
**Pull request by robrix**

### CODE REVIEW

**Comment by robrix** [comment]
Waitasec… are we actually using this fork at all? /cc @robb

**Comment by robb** [comment]
Only in [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa/commit/c52c1018defc64cb3eb269bc8144831edc95cafe) and [Commandant](https://github.com/Carthage/Commandant/commit/4c4cc9b1c381a8e69dd6ed5acdec7c14152de0d6), but not yet in Carthage.

Commandant needs to be tagged at 0.1.1, then we can update the Cartfile in Carthage to use this LlamaKit fork as well as the updated versions of ReactiveCocoa and Commandant.

**Comment by robrix** [comment]
:+1: thanks.

**Comment by robb** [comment]
I filed https://github.com/Carthage/Carthage/issues/163 to keep track of that (should've done that earlier :sweat: )

**Comment by robrix** [comment]
I’m going to close this out and just pull from upstream.

**Pull request closed without merging**
